### ISSUE TITLE
Touchpad on latest LuneOS build boots but no display

### ISSUE THREAD

**Issue by Starkka15** [webOS-ports/webos-ports-setup#18]
Any quick fix for this I can do?

**Comment by Herrie82** [comment]
Hard to say, we're doing quite some fundamental changes to the compositor at the moment and I haven't tested Tenderloin myself yet. I should be able to get to this on Sunday or Monday

**Comment by Starkka15** [comment]
Okay, not a problem. I tried the gstreamer fix, but that did not work for this build.

Thanks!

**Comment by Herrie82** [comment]
I am able to boot to a black screen on my latest test image, however, it seems that we need to make some adjustments to our luna-surfacemanager script that assumes that /sys/class/drm exists which is not the case on Tenderloin as per https://github.com/webOS-ports/luna-surfacemanager/blob/webOS-ports/webOS-OSE/base/startup/product.env.in#L91

"adb shell" works at my end so I can create and pull logs. My log for reference: https://pastebin.ubuntu.com/p/fs4XtxNxD8/

**Comment by Herrie82** [comment]
We're in the middle of the compositor migration, so this wasn't tested yet on a whole range of devices. Only on qemux86-64 and PinePhone(Pro) previously. We will test it on Tenderloin, Mido now to see how we can address this.

**Comment by Herrie82** [comment]
@Starkka15 OK it took some trial and error but it seems stuff builds and boots (quicker) now to UI. The compositor migration isn't fully done yet. I would say we're 80-90% there already, so you will still see weird stuff, but you should get UI when you update the layers and build a new image. I'm happy to upload my image if that's easier.

**Comment by Starkka15** [comment]
Just got home from work (Installing a Wide Format Printer in Buffalo, NY, 3 hours from where I live). I'm compiling now and will update. Thanks for all the hard work you guys put into this.

**Comment by Herrie82** [comment]
We've also fixed a bug that cuts down the boot time by about 2 minutes based on my testing. It's still not very quick (about 2 minutes on the first boot and 1,5 minutes on subsequent boots), but I guess that's to be expected on 10+ years old hardware. As I mentioned this is still very much work in progress for now while the last remaining issues for the UI are being ironed out.

**Comment by Starkka15** [comment]
It definitely boots up to UI. When trying to load apps the UI breaks and icons disappear, I'm assuming that's related to the compositor not being able to load things properly before sending to display?
