### ISSUE TITLE
Localization-tool-native-1.11.0-r9

### ISSUE THREAD

**Issue by Starkka15** [webOS-ports/webos-ports-setup#19]
Went to check progress on patches made since my last issue placed.
My building is running into issues trying to find localization-tool-native-1.11.0-r9

Log: Attached

ENV_NAME=testing

![VirtualBox_Ubuntu22 04_17_05_2023_01_58_57](https://github.com/webOS-ports/webos-ports-setup/assets/98231969/f087fd00-9e62-4bb4-8848-1724ba53438c)

**Comment by Herrie82** [comment]
@Starkka15 This was fixed
